library(foreign)

dataset_aloi <- read.arff("datasets/literature/ALOI/ALOI_withoutdupl.arff")
dataset_glass <- read.arff("datasets/literature/Glass/Glass_withoutdupl_norm.arff")
dataset_iono <- read.arff("datasets/literature/Ionosphere/Ionosphere_withoutdupl_norm.arff")
dataset_kdd <- read.arff("datasets/literature/KDDCup99/KDDCup99_withoutdupl_1ofn.arff")
dataset_lym <- read.arff("datasets/literature/Lymphography/Lymphography_withoutdupl_1ofn.arff")
dataset_pen <- read.arff("datasets/literature/PenDigits/PenDigits_withoutdupl_norm_v01.arff")
dataset_shuttle <- read.arff("datasets/literature/Shuttle/Shuttle_withoutdupl_v01.arff")
dataset_waveform <- read.arff("datasets/literature/Waveform/Waveform_withoutdupl_v01.arff")
dataset_wbc <- read.arff("datasets/literature/WBC/WBC_withoutdupl_v01.arff")
dataset_wdbc <- read.arff("datasets/literature/WDBC/WDBC_withoutdupl_v01.arff")
dataset_wpbc <- read.arff("datasets/literature/WPBC/WPBC_withoutdupl_norm.arff")

dataset_ann <- read.arff("datasets/semantic/Annthyroid/Annthyroid_withoutdupl_07.arff")
dataset_arr <- read.arff("datasets/semantic/Arrhythmia/Arrhythmia_withoutdupl_10_v01.arff")
dataset_cardio <- read.arff("datasets/semantic/Cardiotocography/Cardiotocography_withoutdupl_20_v01.arff")
dataset_heart <- read.arff("datasets/semantic/HeartDisease/HeartDisease_withoutdupl_20_v01.arff")
dataset_hepatitis <- read.arff("datasets/semantic/Hepatitis/Hepatitis_withoutdupl_16.arff")
dataset_ads <- read.arff("datasets/semantic/InternetAds/InternetAds_withoutdupl_norm_19.arff")
dataset_blocks <- read.arff("datasets/semantic/PageBlocks/PageBlocks_withoutdupl_09.arff")
dataset_parkinson <- read.arff("datasets/semantic/Parkinson/Parkinson_withoutdupl_20_v01.arff")
dataset_pima <- read.arff("datasets/semantic/Pima/Pima_withoutdupl_20_v01.arff")
dataset_spam <- read.arff("datasets/semantic/SpamBase/SpamBase_withoutdupl_20_v01.arff")
dataset_stamps <- read.arff("datasets/semantic/Stamps/Stamps_withoutdupl_09.arff")
dataset_wilt <- read.arff("datasets/semantic/Wilt/Wilt_withoutdupl_05.arff")